name: Compilation
on:
  push:

  pull_request:

jobs:
  Compile:
    name: Compile typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: "yarn"

      - name: Install dependencies
        run: yarn
